name: Auto

on:
  schedule:
    # every hour
    - cron: "0 */1 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Run main script
        run: node main.js

      - name: Run scanner script
        run: node scanner.js

      - name: Set commit date
        id: date
        run: echo "COMMIT_DATE=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: output
          keep_history: true
          commit_message: "Auto update ${{ env.COMMIT_DATE }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
